<?xml version="1.0"?>

<robot name="laikago" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find simpledog)/urdf/laikago/const.xacro"/>
    <xacro:include filename="$(find simpledog)/urdf/laikago/materials.xacro"/>
    <xacro:include filename="$(find simpledog)/urdf/laikago/my_laika_leg.xacro"/>
    <xacro:include filename="$(find simpledog)/urdf/laikago/gazebo.xacro"/>

    <!-- Rollover Protection mode will add an additional stick on the top, use "true" or "false" to switch it. -->
    <xacro:property name="rolloverProtection" value="false"/>

    <!-- Debug mode will hung up the robot, use "true" or "false" to switch it. -->
    <xacro:if value="$(arg DEBUG)">
        <link name="world"/>
        <joint name="base_static_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="base"/>
        </joint>
    </xacro:if>

    <link name="base">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="floating_base" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base"/>
        <child link="base_inertia"/>
    </joint>

    <link name="base_inertia">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://simpledog/meshes/laikago/trunk.dae" scale="1 1 1"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${trunk_offset_z}"/>
            <geometry>
                <box size="${trunk_length} ${trunk_width} ${trunk_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="${trunk_com_x} ${trunk_com_y} ${trunk_com_z}"/>
            <mass value="${trunk_mass}"/>
            <inertia
                ixx="${trunk_ixx}" ixy="${trunk_ixy}" ixz="${trunk_ixz}"
                iyy="${trunk_iyy}" iyz="${trunk_iyz}"
                izz="${trunk_izz}"/>
        </inertial>
    </link>

    <xacro:if value="${(rolloverProtection == 'true')}">
        <joint name="stick_joint" type="fixed">
            <parent link="base_inertia"/>
            <child link="stick_link"/>
            <origin rpy="0 0 0" xyz="${0.18} 0 ${stick_length/2.0+0.08}"/>
        </joint>

        <link name="stick_link">
            <visual>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${stick_length}" radius="${stick_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${stick_mass}"/>
                <inertia
                    ixx="${stick_mass / 2.0 * (stick_radius*stick_radius)}" ixy="0.0" ixz="0.0"
                    iyy="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}" iyz="0.0"
                    izz="${stick_mass / 12.0 * (3*stick_radius*stick_radius + stick_length*stick_length)}"/>
            </inertial>
        </link>
    </xacro:if>

    <joint name="imu_joint" type="fixed">
        <parent link="base"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size=".001 .001 .001"/>
            </geometry>
        </collision>
    </link>

   <xacro:include filename="$(find simpledog)/urdf/front_kinect.urdf.xacro"/>
   <xacro:include filename="$(find simpledog)/urdf/stereo.urdf.xacro"/>
   <xacro:include filename="$(find simpledog)/urdf/front_high_kinect.urdf.xacro"/>
   <xacro:include filename="$(find simpledog)/urdf/right_kinect.urdf.xacro"/> 
   <xacro:include filename="$(find simpledog)/urdf/rear_kinect.urdf.xacro"/> 
   <xacro:include filename="$(find simpledog)/urdf/left_kinect.urdf.xacro"/> 
    <!--load kinect urdf-->


<!--load stereo_camera for vins-->
<!--    <xacro:stereo_camera prefix="camera" robot_namespace="$(arg robot_namespace)"/>
    <joint name="stereo_frame_joint" type="fixed">
      <origin xyz="0.28 0.0 0.0" rpy="0 0 0" />
      <parent link="base"/>
      <child link="camera_link"/>
    </joint> -->

      <xacro:front_kinect_camera prefix="camera" robot_namespace="$(arg robot_namespace)"/>
      <joint name="front_kinect_frame_joint" type="fixed">
        <origin xyz="0.30 0 0.0" rpy="0 0.8 0" />
        <parent link="base"/>
        <child link="camera_link"/>
      </joint> 

   <!--   <xacro:rear_kinect_camera prefix="rear_camera" robot_namespace="$(arg robot_namespace)"/>
      <joint name="rear_kinect_frame_joint" type="fixed">
        <origin xyz="-0.28 0 0.0" rpy="0 0.8 3.14" />
        <parent link="base"/>
        <child link="rear_camera_link"/>   
      </joint> -->
    
    <!--load kinect urdf--> 
     
     <!-- <xacro:front_high_kinect_camera prefix="front_high_camera" robot_namespace="$(arg robot_namespace)"/>
      <joint name="front_high_kinect_frame_joint" type="fixed">
        <origin xyz="0.28 0 0.1" rpy="0 0.1 0" />
        <parent link="base"/>
        <child link="front_high_camera_link"/> 
      </joint> --> 

    <!--load kinect urdf-->
    
    <!-- <xacro:right_kinect_camera prefix="right_camera" robot_namespace="$(arg robot_namespace)"/>
      <joint name="right_kinect_frame_joint" type="fixed">
        <origin xyz="-0.0 -0.07 0.0" rpy="0 0.8 -1.57" />
        <parent link="base"/>
        <child link="right_camera_link"/>
      </joint>  

     <xacro:left_kinect_camera prefix="left_camera" robot_namespace="$(arg robot_namespace)"/>
      <joint name="left_kinect_frame_joint" type="fixed">
        <origin xyz="-0.0 0.07 0.0" rpy="0 0.8 1.57" />
        <parent link="base"/>
        <child link="left_camera_link"/>
      </joint> -->
    
    <xacro:include filename="$(find simpledog)/urdf/VLP-16.urdf.xacro"/>
    <VLP-16 parent="base">
        <origin xyz="0.0  0  0.11" rpy="0 0 0" />
    </VLP-16>

    <xacro:leg name="LF" mirror="1" mirror_dae="true" front_hind="1" front_hind_dae="true">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RF" mirror="-1" mirror_dae="false" front_hind="1" front_hind_dae="true">
        <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="RH" mirror="-1" mirror_dae="false" front_hind="-1" front_hind_dae="false">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
    </xacro:leg>

    <xacro:leg name="LH" mirror="1" mirror_dae="true" front_hind="-1" front_hind_dae="false">
        <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
    </xacro:leg>


</robot>
