balance_controller:
  virtual_model_controller:
    heading:
      kp: 650
      kd: 5
      kff: 1
    lateral:
      kp: 700
      kd: 5
      kff: 1
    vertical:
      kp: 700
      kd: 5
      kff: 1
    roll:
      kp: 550
      kd: 5
      kff: 0.2
    pitch:
      kp: 550
      kd: 5
      kff: 0.2
    yaw:
      kp: 550
      kd: 5
      kff: 1
    gravity_compensation_percentage: 1.005
  contact_force_distribution:
    weights:
      force:
        heading: 1
        lateral: 1
        vertical: 1
      torque:
        roll: 10
        pitch: 10
        yaw: 5
      regularizer:
        value: 0.00001
      force_diff:
        value: 1
        is_use: false
    constraints:
      friction_coefficient: 0.6
      minimal_normal_force: 10
      load_factor: 1
single_leg_controller:
  x_direction:
    kp: 150
    kd: 3
  y_direction:
    kp: 150
    kd: 3
  z_direction:
    kp: 150
    kd: 3
